const shipping = [
    {
        method: 'B2C - BUDGETMAIL', countries: [{name: 'Netherlands', cost: 2.50}]
    },
    {
        method: 'B2C - MAILPLUS (TRACKED)',
        countries: [
            {name: 'Netherlands', cost: 5.00},
            {name: 'Belgium', cost: 8.00},
            {name: 'France', cost: 10.00},
        ]
    },
    {
        method: 'B2C - PARCELPLUS (TRACKED)', countries: [
            {name: 'Germany', cost: 6.00},
            {name: 'United Kingdom', cost: 8.50},
            {name: 'Spain', cost: 10.00},
            {name: 'Denmark', cost: 12.00},
            {name: 'Austria', cost: 12.00},
            {name: 'Greece', cost: 12.00},
            {name: 'Czech Republic', cost: 15.00},
            {name: 'Hungary', cost: 15.00},
            {name: 'Poland', cost: 15.00},
            {name: 'Slovakia', cost: 15.00},
            {name: 'Slovenia', cost: 15.00},
            {name: 'Norway', cost: 20.00},
            {name: 'Switzerland', cost: 20.00},
            {name: 'Albania', cost: 42.00},
            {name: 'Belarus', cost: 42.00},
            {name: 'Bosnia and Herzegovina', cost: 42.00},
            {name: 'Macedonia', cost: 42.00},
            {name: 'Moldova', cost: 42.00},
            {name: 'Montenegro', cost: 42.00},
            {name: 'Serbia', cost: 42.00},
            {name: 'Ukraine', cost: 42.00},
            {name: 'Turkey', cost: 42.00}
        ]
    },
    {
        method: 'B2C - PRIORITYMAIL',
        countries: [
            {name: 'Luxembourg', cost: 5.25},
            {name: 'United Kingdom', cost: 8.25},
            {name: 'Andorra', cost: 12.00},
            {name: 'Faroe Islands', cost: 12.00},
            {name: 'Greece', cost: 12.00},
            {name: 'Guernsey', cost: 12.00},
            {name: 'Jersey', cost: 12.00},
            {name: 'Monaco', cost: 12.00},
            {name: 'San Marino', cost: 12.00},
            {name: 'Albania', cost: 20.00},
            {name: 'Belarus', cost: 20.00},
            {name: 'Bosnia and Herzegovina', cost: 20.00},
            {name: 'Bulgaria', cost: 20.00},
            {name: 'Croatia', cost: 20.00},
            {name: 'Gibraltar', cost: 20.00},
            {name: 'Liechtenstein', cost: 20.00},
            {name: 'Macedonia', cost: 20.00},
            {name: 'Malta', cost: 20.00},
            {name: 'Moldova', cost: 20.00},
            {name: 'Montenegro', cost: 20.00},
            {name: 'Serbia', cost: 20.00},
            {name: 'Ukraine', cost: 20.00},
            {name: 'Cyprus', cost: 20.00},
            {name: 'Turkey', cost: 20.00},
        ]
    },
    {
        method: 'FEDEX - INTERNATIONAL (TRACKED)',
        countries: [
            {name: 'Andorra', cost: 12.00},
            {name: 'Faroe Islands', cost: 12.00},
            {name: 'Finland', cost: 12.00},
            {name: 'Guernsey', cost: 12.00},
            {name: 'Ireland', cost: 12.00},
            {name: 'Italy', cost: 12.00},
            {name: 'Jersey', cost: 12.00},
            {name: 'Luxembourg', cost: 12.00},
            {name: 'Monaco', cost: 12.00},
            {name: 'Portugal', cost: 12.00},
            {name: 'San Marino', cost: 12.00},
            {name: 'Sweden', cost: 12.00},
            {name: 'Canada', cost: 30.00},
            {name: 'Cyprus', cost: 30.00},
            {name: 'Gibraltar', cost: 30.00},
            {name: 'Iceland', cost: 30.00},
            {name: 'Liechtenstein', cost: 30.00},
            {name: 'Malta', cost: 30.00},
            {name: 'Australia', cost: 38.00},
            {name: 'New Zealand', cost: 38.00},
            {name: 'Afghanistan', cost: 75.00},
            {name: 'Algeria', cost: 75.00},
            {name: 'American Samoa', cost: 75.00},
            {name: 'Angola', cost: 75.00},
            {name: 'Anguilla', cost: 75.00},
            {name: 'Antarctica', cost: 75.00},
            {name: 'Antigua and Barbuda', cost: 75.00},
            {name: 'Argentina', cost: 75.00},
            {name: 'Armenia', cost: 75.00},
            {name: 'Aruba', cost: 75.00},
            {name: 'Azerbaijan', cost: 75.00},
            {name: 'Bahamas', cost: 75.00},
            {name: 'Bahrain', cost: 75.00},
            {name: 'Bangladesh', cost: 75.00},
            {name: 'Barbados', cost: 75.00},
            {name: 'Belize', cost: 75.00},
            {name: 'Benin', cost: 75.00},
            {name: 'Bermuda', cost: 75.00},
            {name: 'Bhutan', cost: 75.00},
            {name: 'Bolivia', cost: 75.00},
            {name: 'Bonaire', cost: 75.00},
            {name: 'Botswana', cost: 75.00},
            {name: 'Bouvet Island', cost: 75.00},
            {name: 'Brazil', cost: 75.00},
            {name: 'British Indian Ocean Territory', cost: 75.00},
            {name: 'British Virgin Islands', cost: 75.00},
            {name: 'Brunei', cost: 75.00},
            {name: 'Burkina Faso', cost: 75.00},
            {name: 'Burundi', cost: 75.00},
            {name: 'Cambodia', cost: 75.00},
            {name: 'Cameroon', cost: 75.00},
            {name: 'Cape Verde', cost: 75.00},
            {name: 'Cayman Islands', cost: 75.00},
            {name: 'Central African Republic', cost: 75.00},
            {name: 'Chad', cost: 75.00},
            {name: 'Chile', cost: 75.00},
            {name: 'China', cost: 75.00},
            {name: 'Christmas Island', cost: 75.00},
            {name: 'Cocos (Keeling) Islands', cost: 75.00},
            {name: 'Colombia', cost: 75.00},
            {name: 'Comoros', cost: 75.00},
            {name: 'Congo', cost: 75.00},
            {name: 'Cook Islands', cost: 75.00},
            {name: 'Costa Rica', cost: 75.00},
            {name: 'Cuba', cost: 75.00},
            {name: 'Curaçao', cost: 75.00},
            {name: 'Côte dIvoire', cost: 75.00},
            {name: 'Democratic Republic of the Congo', cost: 75.00},
            {name: 'Djibouti', cost: 75.00},
            {name: 'Dominica', cost: 75.00},
            {name: 'Dominican Republic', cost: 75.00},
            {name: 'Ecuador', cost: 75.00},
            {name: 'Egypt', cost: 75.00},
            {name: 'El Salvador', cost: 75.00},
            {name: 'Equatorial Guinea', cost: 75.00},
            {name: 'Eritrea', cost: 75.00},
            {name: 'Ethiopia', cost: 75.00},
            {name: 'Falkland Islands', cost: 75.00},
            {name: 'Fiji', cost: 75.00},
            {name: 'French Guiana', cost: 75.00},
            {name: 'French Polynesia', cost: 75.00},
            {name: 'French Southern Territories', cost: 75.00},
            {name: 'Gabon', cost: 75.00},
            {name: 'Gambia', cost: 75.00},
            {name: 'Georgia', cost: 75.00},
            {name: 'Ghana', cost: 75.00},
            {name: 'Greenland', cost: 75.00},
            {name: 'Grenada', cost: 75.00},
            {name: 'Guadeloupe', cost: 75.00},
            {name: 'Guam', cost: 75.00},
            {name: 'Guatemala', cost: 75.00},
            {name: 'Guinea', cost: 75.00},
            {name: 'Guinea-Bissau', cost: 75.00},
            {name: 'Guyana', cost: 75.00},
            {name: 'Haiti', cost: 75.00},
            {name: 'Heard Island and Mcdonald Islands', cost: 75.00},
            {name: 'Honduras', cost: 75.00},
            {name: 'Hong Kong', cost: 75.00},
            {name: 'India', cost: 75.00},
            {name: 'Indonesia', cost: 75.00},
            {name: 'Iran', cost: 75.00},
            {name: 'Iraq', cost: 75.00},
            {name: 'Israel', cost: 75.00},
            {name: 'Jamaica', cost: 75.00},
            {name: 'Japan', cost: 75.00},
            {name: 'Jordan', cost: 75.00},
            {name: 'Kazakhstan', cost: 75.00},
            {name: 'Kenya', cost: 75.00},
            {name: 'Kiribati', cost: 75.00},
            {name: 'Kosovo', cost: 75.00},
            {name: 'Kuwait', cost: 75.00},
            {name: 'Kyrgyzstan', cost: 75.00},
            {name: 'Laos', cost: 75.00},
            {name: 'Lebanon', cost: 75.00},
            {name: 'Lesotho', cost: 75.00},
            {name: 'Liberia', cost: 75.00},
            {name: 'Libya', cost: 75.00},
            {name: 'Macao', cost: 75.00},
            {name: 'Madagascar', cost: 75.00},
            {name: 'Malawi', cost: 75.00},
            {name: 'Malaysia', cost: 75.00},
            {name: 'Maldives', cost: 75.00},
            {name: 'Mali', cost: 75.00},
            {name: 'Marshall Islands', cost: 75.00},
            {name: 'Martinique', cost: 75.00},
            {name: 'Mauritania', cost: 75.00},
            {name: 'Mauritius', cost: 75.00},
            {name: 'Mayotte', cost: 75.00},
            {name: 'Mexico', cost: 75.00},
            {name: 'Micronesia', cost: 75.00},
            {name: 'Mongolia', cost: 75.00},
            {name: 'Montserrat', cost: 75.00},
            {name: 'Morocco', cost: 75.00},
            {name: 'Mozambique', cost: 75.00},
            {name: 'Myanmar', cost: 75.00},
            {name: 'Namibia', cost: 75.00},
            {name: 'Nauru', cost: 75.00},
            {name: 'Nepal', cost: 75.00},
            {name: 'New Caledonia', cost: 75.00},
            {name: 'Nicaragua', cost: 75.00},
            {name: 'Niger', cost: 75.00},
            {name: 'Nigeria', cost: 75.00},
            {name: 'Niue', cost: 75.00},
            {name: 'Norfolk Island', cost: 75.00},
            {name: 'North Korea', cost: 75.00},
            {name: 'Northern Mariana Islands', cost: 75.00},
            {name: 'Oman', cost: 75.00},
            {name: 'Pakistan', cost: 75.00},
            {name: 'Palau', cost: 75.00},
            {name: 'Palestine', cost: 75.00},
            {name: 'Panama', cost: 75.00},
            {name: 'Papua New Guinea', cost: 75.00},
            {name: 'Paraguay', cost: 75.00},
            {name: 'Peru', cost: 75.00},
            {name: 'Philippines', cost: 75.00},
            {name: 'Pitcairn Islands', cost: 75.00},
            {name: 'Puerto Rico', cost: 75.00},
            {name: 'Qatar', cost: 75.00},
            {name: 'Rwanda', cost: 75.00},
            {name: 'Réunion', cost: 75.00},
            {name: 'Saint Barthélemy', cost: 75.00},
            {name: 'Saint Helena', cost: 75.00},
            {name: 'Saint Kitts and Nevis', cost: 75.00},
            {name: 'Saint Lucia', cost: 75.00},
            {name: 'Saint Martin', cost: 75.00},
            {name: 'Saint Pierre and Miquelon', cost: 75.00},
            {name: 'Saint Vincent and the Grenadines', cost: 75.00},
            {name: 'Samoa', cost: 75.00},
            {name: 'Saudi Arabia', cost: 75.00},
            {name: 'Senegal', cost: 75.00},
            {name: 'Seychelles', cost: 75.00},
            {name: 'Sierra Leone', cost: 75.00},
            {name: 'Singapore', cost: 75.00},
            {name: 'Sint Maarten', cost: 75.00},
            {name: 'Solomon Islands', cost: 75.00},
            {name: 'Somalia', cost: 75.00},
            {name: 'South Africa', cost: 75.00},
            {name: 'South Georgia and the South Sandwich Islands', cost: 75.00},
            {name: 'South Korea', cost: 75.00},
            {name: 'South Sudan', cost: 75.00},
            {name: 'Sri Lanka', cost: 75.00},
            {name: 'Sudan', cost: 75.00},
            {name: 'Suriname', cost: 75.00},
            {name: 'Switzerland', cost: 75.00},
            {name: 'Syria', cost: 75.00},
            {name: 'São Tomé and Príncipe', cost: 75.00},
            {name: 'Taiwan', cost: 75.00},
            {name: 'Tajikistan', cost: 75.00},
            {name: 'Tanzania', cost: 75.00},
            {name: 'Thailand', cost: 75.00},
            {name: 'Timor-Leste', cost: 75.00},
            {name: 'Togo', cost: 75.00},
            {name: 'Tokelau', cost: 75.00},
            {name: 'Tonga', cost: 75.00},
            {name: 'Trinidad and Tobago', cost: 75.00},
            {name: 'Tunisia', cost: 75.00},
            {name: 'Turkmenistan', cost: 75.00},
            {name: 'Turks and Caicos Islands', cost: 75.00},
            {name: 'Tuvalu', cost: 75.00},
            {name: 'Uganda', cost: 75.00},
            {name: 'United Arab Emirates', cost: 75.00},
            {name: 'United States Minor Outlying Islands', cost: 75.00},
            {name: 'United States Virgin Islands', cost: 75.00},
            {name: 'Uruguay', cost: 75.00},
            {name: 'Uzbekistan', cost: 75.00},
            {name: 'Vanuatu', cost: 75.00},
            {name: 'Venezuela', cost: 75.00},
            {name: 'Vietnam', cost: 75.00},
            {name: 'Wallis and Futuna', cost: 75.00},
            {name: 'Western Sahara', cost: 75.00},
            {name: 'Yemen', cost: 75.00},
            {name: 'Zambia', cost: 75.00},
            {name: 'Zimbabwe', cost: 75.00}
        ]
    },
    {
        method: 'FEDEX - HOME DELIVERY (TRACKED)', countries: [{name: 'United States', cost: 13.20}]
    },
    {
        method: 'FEDEX - SMARTPOST BPM', countries: [{name: 'United States', cost: 5.06}]
    },
    {
        method: 'SWISS POST - PRIORITY',
        countries: [
            {name: 'Germany', cost: 4.50},
            {name: 'Belgium', cost: 6.0},
            {name: 'France', cost: 6.00},
            {name: 'Austria', cost: 8.00},
            {name: 'Italy', cost: 8.00},
            {name: 'Switzerland', cost: 8.00},
            {name: 'Canada', cost: 10.00},
            {name: 'Japan', cost: 10.00},
            {name: 'Estonia', cost: 10.00},
            {name: 'Iceland', cost: 10.00},
            {name: 'Latvia', cost: 10.00},
            {name: 'Lithuania', cost: 10.00},
            {name: 'Portugal', cost: 10.00},
            {name: 'Spain', cost: 10.00},
            {name: 'Finland', cost: 12.00},
            {name: 'Ireland', cost: 12.00},
            {name: 'Norway', cost: 12.00},
            {name: 'Sweden', cost: 12.00},
            {name: 'Australia', cost: 15.00},
            {name: 'New Zealand', cost: 15.00},
            {name: 'Afghanistan', cost: 32.00},
            {name: 'Algeria', cost: 32.00},
            {name: 'American Samoa', cost: 32.00},
            {name: 'Angola', cost: 32.00},
            {name: 'Anguilla', cost: 32.00},
            {name: 'Antarctica', cost: 32.00},
            {name: 'Antigua and Barbuda', cost: 32.00},
            {name: 'Argentina', cost: 32.00},
            {name: 'Armenia', cost: 32.00},
            {name: 'Aruba', cost: 32.00},
            {name: 'Azerbaijan', cost: 32.00},
            {name: 'Bahamas', cost: 32.00},
            {name: 'Bahrain', cost: 32.00},
            {name: 'Bangladesh', cost: 32.00},
            {name: 'Barbados', cost: 32.00},
            {name: 'Belize', cost: 32.00},
            {name: 'Benin', cost: 32.00},
            {name: 'Bermuda', cost: 32.00},
            {name: 'Bhutan', cost: 32.00},
            {name: 'Bolivia', cost: 32.00},
            {name: 'Bonaire', cost: 32.00},
            {name: 'Botswana', cost: 32.00},
            {name: 'Bouvet Island', cost: 32.00},
            {name: 'Brazil', cost: 32.00},
            {name: 'British Indian Ocean Territory', cost: 32.00},
            {name: 'British Virgin Islands', cost: 32.00},
            {name: 'Brunei', cost: 32.00},
            {name: 'Burkina Faso', cost: 32.00},
            {name: 'Burundi', cost: 32.00},
            {name: 'Cambodia', cost: 32.00},
            {name: 'Cameroon', cost: 32.00},
            {name: 'Cape Verde', cost: 32.00},
            {name: 'Cayman Islands', cost: 32.00},
            {name: 'Central African Republic', cost: 32.00},
            {name: 'Chad', cost: 32.00},
            {name: 'Chile', cost: 32.00},
            {name: 'China', cost: 32.00},
            {name: 'Christmas Island', cost: 32.00},
            {name: 'Cocos (Keeling) Islands', cost: 32.00},
            {name: 'Colombia', cost: 32.00},
            {name: 'Comoros', cost: 32.00},
            {name: 'Congo', cost: 32.00},
            {name: 'Cook Islands', cost: 32.00},
            {name: 'Costa Rica', cost: 32.00},
            {name: 'Cuba', cost: 32.00},
            {name: 'Curaçao', cost: 32.00},
            {name: 'Côte dIvoire', cost: 32.00},
            {name: 'Democratic Republic of the Congo', cost: 32.00},
            {name: 'Djibouti', cost: 32.00},
            {name: 'Dominica', cost: 32.00},
            {name: 'Dominican Republic', cost: 32.00},
            {name: 'Ecuador', cost: 32.00},
            {name: 'Egypt', cost: 32.00},
            {name: 'El Salvador', cost: 32.00},
            {name: 'Equatorial Guinea', cost: 32.00},
            {name: 'Eritrea', cost: 32.00},
            {name: 'Ethiopia', cost: 32.00},
            {name: 'Falkland Islands', cost: 32.00},
            {name: 'Fiji', cost: 32.00},
            {name: 'French Guiana', cost: 32.00},
            {name: 'French Polynesia', cost: 32.00},
            {name: 'French Southern Territories', cost: 32.00},
            {name: 'Gabon', cost: 32.00},
            {name: 'Gambia', cost: 32.00},
            {name: 'Georgia', cost: 32.00},
            {name: 'Ghana', cost: 32.00},
            {name: 'Greenland', cost: 32.00},
            {name: 'Grenada', cost: 32.00},
            {name: 'Guadeloupe', cost: 32.00},
            {name: 'Guam', cost: 32.00},
            {name: 'Guatemala', cost: 32.00},
            {name: 'Guinea', cost: 32.00},
            {name: 'Guinea-Bissau', cost: 32.00},
            {name: 'Guyana', cost: 32.00},
            {name: 'Haiti', cost: 32.00},
            {name: 'Heard Island and Mcdonald Islands', cost: 32.00},
            {name: 'Honduras', cost: 32.00},
            {name: 'Hong Kong', cost: 32.00},
            {name: 'India', cost: 32.00},
            {name: 'Indonesia', cost: 32.00},
            {name: 'Iran', cost: 32.00},
            {name: 'Iraq', cost: 32.00},
            {name: 'Israel', cost: 32.00},
            {name: 'Jamaica', cost: 32.00},
            {name: 'Japan', cost: 32.00},
            {name: 'Jordan', cost: 32.00},
            {name: 'Kazakhstan', cost: 32.00},
            {name: 'Kenya', cost: 32.00},
            {name: 'Kiribati', cost: 32.00},
            {name: 'Kosovo', cost: 32.00},
            {name: 'Kuwait', cost: 32.00},
            {name: 'Kyrgyzstan', cost: 32.00},
            {name: 'Laos', cost: 32.00},
            {name: 'Lebanon', cost: 32.00},
            {name: 'Lesotho', cost: 32.00},
            {name: 'Liberia', cost: 32.00},
            {name: 'Libya', cost: 32.00},
            {name: 'Macao', cost: 32.00},
            {name: 'Madagascar', cost: 32.00},
            {name: 'Malawi', cost: 32.00},
            {name: 'Malaysia', cost: 32.00},
            {name: 'Maldives', cost: 32.00},
            {name: 'Mali', cost: 32.00},
            {name: 'Marshall Islands', cost: 32.00},
            {name: 'Martinique', cost: 32.00},
            {name: 'Mauritania', cost: 32.00},
            {name: 'Mauritius', cost: 32.00},
            {name: 'Mayotte', cost: 32.00},
            {name: 'Mexico', cost: 32.00},
            {name: 'Micronesia', cost: 32.00},
            {name: 'Mongolia', cost: 32.00},
            {name: 'Montserrat', cost: 32.00},
            {name: 'Morocco', cost: 32.00},
            {name: 'Mozambique', cost: 32.00},
            {name: 'Myanmar', cost: 32.00},
            {name: 'Namibia', cost: 32.00},
            {name: 'Nauru', cost: 32.00},
            {name: 'Nepal', cost: 32.00},
            {name: 'New Caledonia', cost: 32.00},
            {name: 'Nicaragua', cost: 32.00},
            {name: 'Niger', cost: 32.00},
            {name: 'Nigeria', cost: 32.00},
            {name: 'Niue', cost: 32.00},
            {name: 'Norfolk Island', cost: 32.00},
            {name: 'North Korea', cost: 32.00},
            {name: 'Northern Mariana Islands', cost: 32.00},
            {name: 'Oman', cost: 32.00},
            {name: 'Pakistan', cost: 32.00},
            {name: 'Palau', cost: 32.00},
            {name: 'Palestine', cost: 32.00},
            {name: 'Panama', cost: 32.00},
            {name: 'Papua New Guinea', cost: 32.00},
            {name: 'Paraguay', cost: 32.00},
            {name: 'Peru', cost: 32.00},
            {name: 'Philippines', cost: 32.00},
            {name: 'Pitcairn Islands', cost: 32.00},
            {name: 'Puerto Rico', cost: 32.00},
            {name: 'Qatar', cost: 32.00},
            {name: 'Rwanda', cost: 32.00},
            {name: 'Réunion', cost: 32.00},
            {name: 'Saint Barthélemy', cost: 32.00},
            {name: 'Saint Helena', cost: 32.00},
            {name: 'Saint Kitts and Nevis', cost: 32.00},
            {name: 'Saint Lucia', cost: 32.00},
            {name: 'Saint Martin', cost: 32.00},
            {name: 'Saint Pierre and Miquelon', cost: 32.00},
            {name: 'Saint Vincent and the Grenadines', cost: 32.00},
            {name: 'Samoa', cost: 32.00},
            {name: 'Saudi Arabia', cost: 32.00},
            {name: 'Senegal', cost: 32.00},
            {name: 'Seychelles', cost: 32.00},
            {name: 'Sierra Leone', cost: 32.00},
            {name: 'Singapore', cost: 32.00},
            {name: 'Sint Maarten', cost: 32.00},
            {name: 'Solomon Islands', cost: 32.00},
            {name: 'Somalia', cost: 32.00},
            {name: 'South Africa', cost: 32.00},
            {name: 'South Georgia and the South Sandwich Islands', cost: 32.00},
            {name: 'South Korea', cost: 32.00},
            {name: 'South Sudan', cost: 32.00},
            {name: 'Sri Lanka', cost: 32.00},
            {name: 'Sudan', cost: 32.00},
            {name: 'Suriname', cost: 32.00},
            {name: 'Switzerland', cost: 32.00},
            {name: 'Syria', cost: 32.00},
            {name: 'São Tomé and Príncipe', cost: 32.00},
            {name: 'Taiwan', cost: 32.00},
            {name: 'Tajikistan', cost: 32.00},
            {name: 'Tanzania', cost: 32.00},
            {name: 'Thailand', cost: 32.00},
            {name: 'Timor-Leste', cost: 32.00},
            {name: 'Togo', cost: 32.00},
            {name: 'Tokelau', cost: 32.00},
            {name: 'Tonga', cost: 32.00},
            {name: 'Trinidad and Tobago', cost: 32.00},
            {name: 'Tunisia', cost: 32.00},
            {name: 'Turkmenistan', cost: 32.00},
            {name: 'Turks and Caicos Islands', cost: 32.00},
            {name: 'Tuvalu', cost: 32.00},
            {name: 'Uganda', cost: 32.00},
            {name: 'United Arab Emirates', cost: 32.00},
            {name: 'United States Minor Outlying Islands', cost: 32.00},
            {name: 'United States Virgin Islands', cost: 32.00},
            {name: 'Uruguay', cost: 32.00},
            {name: 'Uzbekistan', cost: 32.00},
            {name: 'Vanuatu', cost: 32.00},
            {name: 'Venezuela', cost: 32.00},
            {name: 'Vietnam', cost: 32.00},
            {name: 'Wallis and Futuna', cost: 32.00},
            {name: 'Western Sahara', cost: 32.00},
            {name: 'Yemen', cost: 32.00},
            {name: 'Zambia', cost: 32.00},
            {name: 'Isle of Man', cost: 32.00},
            {name: 'Romania', cost: 32.00},
            {name: 'Svalbard and JJan Mayen', cost: 32.00},
            {name: 'Vatican City', cost: 32.00},
            {name: 'Åland Islands', cost: 32.00}

        ]
    },
    {
        method: 'UPS - STANDARD (TRACKED)',
        countries: [
            {name: 'Bulgaria', cost: 20.00},
            {name: 'Croatia', cost: 20.00}
        ]
    },

];
export default shipping;


